---
title: Bioc 2015 GoogleGenomics Workshop
output:
  BiocStyle::html_document
---

<!-- Copyright 2014 Google Inc. All rights reserved. -->

<!-- Licensed under the Apache License, Version 2.0 (the "License"); -->
<!-- you may not use this file except in compliance with the License. -->
<!-- You may obtain a copy of the License at -->

<!--     http://www.apache.org/licenses/LICENSE-2.0 -->

<!-- Unless required by applicable law or agreed to in writing, software -->
<!-- distributed under the License is distributed on an "AS IS" BASIS, -->
<!-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. -->
<!-- See the License for the specific language governing permissions and -->
<!-- limitations under the License. -->

<!--
%% \VignetteEngine{knitr::rmarkdown}
%% \VignetteIndexEntry{GoogleGenomics Demo}
-->

```{r style, echo = FALSE, results = 'asis'}
BiocStyle::markdown()
```

```{r}
help(package="GoogleGenomics")
```

Then click on "User guides, package vignettes and other documentation."

```{r eval=FALSE}
file.edit(file.path(system.file(package = "GoogleGenomics"), "doc", "PlottingAlignments.Rmd"))
file.show(file.path(system.file(package = "GoogleGenomics"), "doc", "PlottingAlignments.html"))
```

```{r eval=FALSE}
file.edit(file.path(system.file(package = "GoogleGenomics"), "doc", "VariantAnnotation-comparison-test.Rmd"))
file.show(file.path(system.file(package = "GoogleGenomics"), "doc", "VariantAnnotation-comparison-test.html"))
```

```{r}
help(package="Bioc2015Workshop")
```

Then click on "User guides, package vignettes and other documentation."

```{r eval=FALSE}
file.edit(file.path(system.file(package = "Bioc2015Workshop"), "doc", "BigQueryDemo.Rmd"))
file.show(file.path(system.file(package = "Bioc2015Workshop"), "doc", "BigQueryDemo.html"))
```

```{r eval=FALSE}
file.edit(file.path(system.file(package = "Bioc2015Workshop"), "doc", "AllModalitiesDemo.Rmd"))
file.show(file.path(system.file(package = "Bioc2015Workshop"), "doc", "AllModalitiesDemo.html"))
```